name: Dummy CI

on:
  push:
    branches: [master]
  pull_request:
    # branches: [master]
    # types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  dummy:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - run: echo "Dummy CI completed"
