name: e2e-tests Skip

on:
  pull_request:
    paths-ignore:
      - 'Bitkit/**'
      - 'BitkitNotification/**'
      - 'BitkitTests/**'
      - 'BitkitUITests/**'
      - 'Bitkit.xcodeproj/**'
      - 'Package.swift'
      - '.github/workflows/e2e-tests.yml'

jobs:
  e2e-status:
    if: github.event.pull_request.draft == false
    name: e2e-status
    runs-on: ubuntu-latest
    steps:
      - run: echo "E2E skipped - no code changes"
